export const IMAGES: Record<string, string> = {
  avatar: "/assets/images/avatar_2.jpg",
  project_1: "/assets/images/project_1.png",
  project_2: "/assets/images/project_2.png",
  photo_1_1: "/assets/images/photo_1.1.jpg",
  photo_1_2: "/assets/images/photo_1.2.jpg",
  photo_2_1: "/assets/images/photo_2.1.jpg",
  photo_2_2: "/assets/images/photo_2.2.jpg",
  photo_3_1: "/assets/images/photo_3.1.jpg",
  photo_3_2: "/assets/images/photo_3.2.jpg",
  photo_4_1: "/assets/images/photo_4.1.jpg",
  photo_4_2: "/assets/images/photo_4.2.jpg",
  photo_5_1: "/assets/images/photo_5.1.jpg",
  photo_5_2: "/assets/images/photo_5.2.jpg",
};
